name: Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  check-php-syntax:
    name: Check PHP Syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
  install:
    name: Install (Concrete v${{ matrix.ccm-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ccm-version:
          - 8
          - 9
    container: ghcr.io/concrete5-community/docker5:${{ matrix.ccm-version }}
    steps:
      -
        name: Start Services
        run: ccm-service start db
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Link package
        run: ln -s "$(pwd)" /app/packages/pixel2to9
      -
        name: Install package
        run: sudo -Hu www-data /app/concrete/bin/concrete5 c5:package-install pixel2to9
